sudo: false

language: node_js

node_js:
  - 6
  - 4
  - 0.12

cache:
  directories:
    - node_modules
before_install:
  - npm cache clean
install:
  - npm install -g jshint
  - npm install -g npm@latest
  - npm install

script:
  - 'jshint lib/'
